### ISSUE TITLE
The character $ in a question can be confusing.

### ISSUE THREAD

**Issue by bobkummerfeld** [gpoore/text2qti#11]
A question like: 
Quiz title: Shell if
1.  What does this script print: NAME=Alice; if [ $NAME == Alice ] ; then echo Hi Alice!; fi

causes an infinite loop. If I remove the $ it works. I assume this is interacting with the LaTex math syntax. $$ seems to work..   

I suggest adding to the documentation to point this out.

**Comment by bobkummerfeld** [comment]
$$ is shown as $$ on the question.  Is there a way of getting a single $ in the question?

**Comment by gpoore** [comment]
It should work now in the dev version after the last commit; the `$` will just pass through as `$` if it isn't followed by another `$` later that fulfills the LaTeX math pattern. The regex for finding LaTeX math was causing catastrophic backtracking.

**Comment by bobkummerfeld** [comment]
Works fine now - thanks!
