### ISSUE TITLE
Expected Question Issue

### ISSUE THREAD

**Issue by TB-iTeach** [gpoore/text2qti#12]
I've been tasked with converting several large 50~100 question quizzes from an old custom LMS to canvas. They've been manually stripped from the old LMS and I've run them through a basic python script to format them to fit the requirements of text2qti. 

When I try and convert to QTI using text2qti, I'm getting the error:

``text2qti.err.Text2qtiError: In "PPR1-stripped-formatted.txt" on line 145:
Expected question; question title and/or points were set but not used``

The issue with this is the line its telling me is innocuous. Here is line 145 and the surrounding questions for context.

```
Title: Question 20
20. Ms. Smith notices that several students seem apprehensive about their role during the planned visit. She decides to give students the option of working with a partner to observe and interview children on the playground. This strategy best demonstrates Ms. Smith's understanding that adolescent students are likely to benefit from: 
*A) peer support in unfamiliar social contexts 
B) interacting with peers during instructional activities 
C) modeling from the teacher when developing new skills 
D) instructional activities that involve peer assessment 

Title: Question 21
<LINE 145>21.   Activity Three is most likely to address which of the following instructional objectives?
A) fostering students' ability to make connections across different content areas 
B) helping students become self-motivated when addressing new challenges 
*C) fostering the development of students' critical-thinking and problem-solving skills 
D) helping students use prior knowledge to formulate conclusions 

Title: Question 22
22. Allowing students to choose among a variety of materials to create their model play structures is likely to support learning most by: 
A) prompting students to reflect on their academic strengths and needs 
*B) encouraging students to analyze the limitations of various options 
C) creating a classroom climate of mutual respect among students 
D) encouraging students to assess their own performance 
```

I'm just wondering what would cause this? Is it some extraneous formatting that can't be visibly seen?

**Comment by gpoore** [comment]
In the example you gave, there is an `L SEP` character between the `21. ` and `Activity`. That's probably the issue; only spaces and tabs are allowed between the number and the question start. If this is the only sort of place where these characters are showing up, then you may be able to do something as simple as `.replace('\u2028', '')` in your preprocessing...you'll probably want to check that, though, since it's possible `\u2028` is also showing up in places where you really want `\n`.

**Comment by gpoore** [comment]
It might also be worth checking to see if `\u2029` is showing up anywhere.

**Comment by TB-iTeach** [comment]
Thanks! This is a huge help! Text formatting isn't an area I'm extremely familiar with.
