### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by mroughan** [gpoore/text2qti#13]
I haven't been able to find a way to add a table to a question?

**Comment by gpoore** [comment]
You should be able to use tables like this: https://python-markdown.github.io/extensions/tables/.

More advanced tables are probably possible, but would require using a Python-Markdown extension beyond what is included in Python-Markdown itself.

**Comment by mroughan** [comment]
When I tried it, I could get the text of the table into Canvas, but the table wasn't parsed as such. It just came out as one long string of text. Maybe there is something I need to do with indentation?

**Comment by dragonxtek** [comment]
remember that you can also use tables in html

**Comment by gpoore** [comment]
I've investigated further, and there are a couple of different issues.

Tables are working (if you are using text2qti v0.2.0 or later), but by default Canvas doesn't use borders for tables (at least for me), so depending on what you are doing, tables don't necessarily look that good. In the last commit (dev version), I've enabled Markdown in HTML, so you can now do something like this to put a box around the entire table:
```
1.  <div markdown="1" style="border: 1px solid black; display: inline-block;">

    First Header  | Second Header
    ------------- | -------------
    Content Cell  | Content Cell
    Content Cell  | Content Cell

    </div>

    More text

*a) True
b)  False
```
Depending on what you are doing, that may be an improvement. However, there isn't a way to modify the table HTML itself without actually writing out the HTML. Python-Markdown doesn't seem to supply an easy way to modify tag attributes for things like tables.

**Comment by mroughan** [comment]
I can use HTML if needed. The plan is to autogenerate the txt files eventually so HTML isn't much harder than markdown for the occasional table. I just hadn't realized I could insert HTML in there.
