### ISSUE TITLE
Quiz description isn't work in Canvas

### ISSUE THREAD

**Issue by dragonxtek** [gpoore/text2qti#15]
I made quizzes with Quiz title, Quiz description and Title, but only Quiz title works.
Where are the contents of those parameters supposed to appear? I've never seen them in the quizzes I've created
Probably doesn't work in some canvas implementations

**Comment by gpoore** [comment]
As far as I know, Canvas always ignores the quiz description ("Quiz description:") and the titles for questions ("Title:"). If you want a quiz description, you can try typing it in manually using the Canvas quiz editor.

**Comment by dragonxtek** [comment]
that's exactly what I was doing, but I wondered if it was a bug or not.
Thanks anyway.

**Comment by gpoore** [comment]
After the bug fix from #18, quiz descriptions work, and question titles will appear correctly in the Canvas quiz editor (but are always replaced with things like "Question 1" in the student view).
