### ISSUE TITLE
Question Titles not showing up in Canvas

### ISSUE THREAD

**Issue by CarterAndrewsITS** [gpoore/text2qti#16]
I read in the documentation that "Canvas may ignore the quiz description and question titles." Can you give any additional details? Is there something that can done with Canvas to make question titles more consistent?

**Comment by gpoore** [comment]
I'm not aware of any in-depth documentation about how Canvas imports QTI and what features are supported, so a lot of this is basically experimental. For me, Canvas always ignores quiz descriptions and question titles. I'm aware of a few other people that have had the same experience, and I think I have also come across a few mentions of the same behavior online. So it appears that these are always ignored, and I may change the wording in the documentation to reflect that at some point. However, the Canvas configuration that I am using does not include the New Quizzes feature, so it is possible that other Canvas versions or configurations might be able to use these features--I just only have access to one version/configuration for testing and experimentation.

**Comment by gpoore** [comment]
After the bug fix from #18, custom question titles do now appear in the instructor's quiz editor in Canvas. However, custom titles are still replaced by titles like "Question 1" in the student view, so this may not be that helpful.
