### ISSUE TITLE
Example in README fails (with question title)

### ISSUE THREAD

**Issue by JeffFessler** [gpoore/text2qti#23]
I pasted the example from the README into a file and tried `text2qti` on it and it failed (on a Mac):

```
/Users/fessler/Library/Python/3.8/bin/text2qti try0.txt
Traceback (most recent call last):
  File "/Users/fessler/Library/Python/3.8/lib/python/site-packages/text2qti/quiz.py", line 450, in __init__
    parse_actions[action](text)
  File "/Users/fessler/Library/Python/3.8/lib/python/site-packages/text2qti/quiz.py", line 657, in append_unknown
    raise Text2qtiError(f'Syntax error; unexpected text, or incorrect indentation for a wrapped paragraph:\n"{text}"')
text2qti.err.Text2qtiError: Syntax error; unexpected text, or incorrect indentation for a wrapped paragraph:
"Title: An addition question"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fessler/Library/Python/3.8/bin/text2qti", line 33, in <module>
    sys.exit(load_entry_point('text2qti==0.4.0', 'console_scripts', 'text2qti')())
  File "/Users/fessler/Library/Python/3.8/lib/python/site-packages/text2qti/cmdline.py", line 82, in main
    quiz = Quiz(text, config=config, source_name=file_path.as_posix())
  File "/Users/fessler/Library/Python/3.8/lib/python/site-packages/text2qti/quiz.py", line 454, in __init__
    raise Text2qtiError(f'In {self.source_name} on line {n+1}:\n{e}')
text2qti.err.Text2qtiError: In "try0.txt" on line 4:
Syntax error; unexpected text, or incorrect indentation for a wrapped paragraph:
"Title: An addition question"
```
If I delete the `Title: ` and `Points: ` lines in the example then it works fine.
I would love to get question titles to work, based on #19, but I am baffled why the example is failing.

**Comment by gpoore** [comment]
Based on the line numbers from the errors, I suspect that you have version 0.2.0 and need to upgrade to 0.4.0 to get the features that aren't working.

**Comment by JeffFessler** [comment]
Thanks so much for the feedback.  You were right - I had an old version ahead of the new version in my path.
I'd like to report that the corrections in PR #19 worked for me (just the two lines mentioned in the PR) and the question titles do appear in Canvas now for the instructor mode of editing questions.  The students don't see the question titles (appropriately so).
The PR #20 was also very helpful for me.
(Even though I have sudo access, it feels safer to install it only in my own workspace.)
Thank you so much for this terrific utility!

**Comment by gpoore** [comment]
Thanks for the report on #19 and #20. Those will go into the next version as soon as I have time to do another release.

**Comment by JeffFessler** [comment]
Let me also report that the "shuffle answers" option is working for me in Canvas too.  Yay!
