### ISSUE TITLE
groups of linked questions

### ISSUE THREAD

**Issue by tdlong** [gpoore/text2qti#24]
You package is a life saver.  Canvas is terrible.  Keep up the great work.

This isn't an issue but a question.  Is there any way to link questions?  Or is this just a limitation of Canvas?  It would be really wonderful to have the ability to use two part questions that are always linked together.  And to further have the ability to randomly pull from several such pairs.  Something like this:

GROUP
pick: 1

LINK
next_n_questions: 2
1A ...
1B ...

LINK
next_n_questions: 2
2A ...
2B ...

END_GROUP

**Comment by gpoore** [comment]
I don't think there is a way to do this.

Currently, I would probably combine questions, something like this:

```
Question 1? Question 2?
*a) Correct 1 and correct 2
b)  Correct 1 and incorrect 2
c)  Incorrect 1 and correct 2
d)  Incorrect 1 and incorrect 2
```

Depending on how complex things are, you might use an executable code block to automatically generate permutations of incorrect answer combinations.

There is a [fork](https://github.com/substance9/text2qti) with at least some support for multiple answers questions and multiple dropdowns questions. If I end up adding support for those types of questions, that could be another option for some scenarios.

**Comment by tdlong** [comment]
It is helpful to know this is a limitation.  Along these lines two four answer multiple choice questions can be represented as a single 8 answer block where the question says for part 1 select the most correct answer from A-D, and for part 2 select the most correct answer from E-H.  And make the question worth 2 points. 

Nested grouping (and linked questions) would allow flexibility in having Canvas generate quizzes from test banks where you want questions on certain topics to be chosen.  Because of covid-19 we are moving course online, so it is suddenly important to have several dozen tests generated.
