### ISSUE TITLE
Warnings when installing w/o sudo privileges

### ISSUE THREAD

**Issue by mikegilchrist** [gpoore/text2qti#33]
It would be helpful for the python novice if an error was thrown if one tried installing the package without root privileges and without the '--user' option.

**Comment by gpoore** [comment]
Is this for installation of the development version, or for pip install? I would hope that a novice would use pip, but in that case I also don't know that it's really possible to try to detect the usage of pip plus privileges and then raise some sort of error. I could add a note about `pip install --user` to the documentation.

**Comment by mikegilchrist** [comment]
I used pip and when I did the install w/o --user, the executable wasn't found by my shell (Ubuntu 18.04).  Where would it install if I used pip w/o root privileges?

**Comment by gpoore** [comment]
There may be `$PATH` issues. Apparently Ubuntu with `--user` installs to `~/.local/bin`, but that location is not part of `$PATH` by default...there's a pip issue related to this from a few years back: https://github.com/pypa/pip/issues/3813.

**Comment by mikegilchrist** [comment]
Hmmmm.. That can't be it because ~/.local/bin was already in my path.  Again, the issue was when I installed using python pip w/o --user option.

**Comment by gpoore** [comment]
Do you just have the default Ubuntu Python installed, or are there other Python installations? I don't have access to a recent Ubuntu installation that I can test with, so my ability to help with this is limited.

**Comment by mikegilchrist** [comment]
Ahhh.  I think I solved it, `$ which python` gives `~/anaconda3/bin/python` and lo and behold there's the text2qti executable.  I guess I need to deepen my understanding of python and/or add this to my path.  I'll do the latter.

Sorry for the trouble. Thanks again for creating the script.  I find it very useful.
