### ISSUE TITLE
Question must provide choices

### ISSUE THREAD

**Issue by CasperClous** [gpoore/text2qti#37]
Hello, hope you are ok, I'm having a problem, I try to make a var question with python inside, and there is a problem, it’s says Question must provide choices.

GROUP
pick: 1
{.python3 .run}
import random
import textwrap

for num in range(0, 4):
	print(textwrap.dedent(rf"""1. <div class="id" id={num}> <p>write something</p>
	____
	"""))

END_GROUP

![image](https://user-images.githubusercontent.com/45837640/100264656-e069dc80-2f2d-11eb-8d10-945aba48613e.png)

I have been looking to the same problem, and have seen that you have fixed something similar, but its may seems that persist.

I'm not an expert and be hoping is not a problem with the text its self.

**Comment by dragonxtek** [comment]
You need to leave the following line alone:

`print(textwrap.dedent(rf"""`

It would be good to do something to improve the compatibility of the string within the print, since that is where most of the errors are generated.

**Comment by gpoore** [comment]
@CasperClous you probably want something like this:
``````
GROUP
pick: 1
```{.python3 .run}
import random
import textwrap

for num in range(0, 4):
    print(textwrap.dedent(rf"""
        1.  write something

            write more

        ____
        """))
```
END_GROUP
``````
The `rf"""` needs to be the very last thing on its line for `textwrap.dedent()` to work. The alternative is to avoid dedenting, which will then look something like this:
``````
GROUP
pick: 1
```{.python3 .run}
import random

for num in range(0, 4):
    print(rf"""
1.  write something

    write more

    ____
""")
```
END_GROUP
``````

**Comment by CasperClous** [comment]
Thanks both of you for the answer, I solved it :D
