### ISSUE TITLE
it is possible regex support on fill-in-the-blank questions?

### ISSUE THREAD

**Issue by Naikelin** [gpoore/text2qti#39]
First of all, thank you for the package! 
As the title says, it is possible to use regex on fill-in-the-blank questions? if it is possible, how it works?

**Comment by gpoore** [comment]
I don't believe there is a way to use regex or similar approaches with QTI version 1.2, which is what text2qti supports. QTI 2.0+ apparently does offer at least some regex support for some question types, but I haven't looked into that.

If I'm working with a non-trivial fill-in-the-blank question, I will typically use an executable code block to automatically generate all permutations of title case, lower case, etc. That's not as good as regex, but it can be better than typing all the options when there are a lot of valid possibilities.
