### ISSUE TITLE
Group questions pick number

### ISSUE THREAD

**Issue by alegione** [gpoore/text2qti#44]
Hi there,
I'm running into a slight issue around picking questions from a group at random. The current code has the requirement that a group must have the number of questions to be picked, plus 1, to be valid. However Canvas does not require this, it only requires the number to match the total picked questions (e.g. pick 30 questions from a pool of 30). This functionality allows the shuffling of questions in a group, rather than shuffling the whole quiz. So that way all students are tested on the same content within the group whilst tweaking the order so that they're not getting the same questions simultaneously. This allows a situation where you want say 20 MCQs to be given randomly, from a pool of 20, whilst also having short answer/essay style questions given in the same order. This approach can be helpful for marking the long answer questions 'question at a time' for example. 

My query is, can the code be adjusted to remove the +1 requirement/error, or is this an underlying problem with the qti format that will throw an error, and the code error message is just being provided to prevent that underlying error arising?

I'm no Python expert but I can try a pull request if that would be helpful (and if the solution is just about the code, rather than the qti format).

Thanks for the great tool, it's been incredibly valuable since we moved to the Canvas quiz system last year.

**Comment by gpoore** [comment]
Thanks for pointing out this scenario with question groups. The +1 requirement was an overly strict requirement left over from when I was first getting things working. I've just fixed it in the last commit on GitHub.

I will be releasing a new version and updating PyPI by sometime in August as I prepare for the start of my fall semester. If you need a new version before that, let me know and I can probably just do two releases, one now and one sometime in August.

**Comment by alegione** [comment]
That's great, thanks very much, it's not critical as I can work around it by adding a dummy question in the short term, just something that was in my mind as I was writing an exam and thought I'd raise it here rather than just thinking it to myself :)

No need for the double release, I can just pull the latest version directly from github rather than using pip if that's a simple solve for now.

Thanks again for the tool, it's saved me literal hours!
