### ISSUE TITLE
Add support for item banks

### ISSUE THREAD

**Issue by rzach** [gpoore/text2qti#5]
Would be nice if one could have `text2qti` package the quiz as a test bank (so that Canvas and other LMS import the questions into the question library rather than as a quiz).

**Comment by gpoore** [comment]
When you import a quiz in Canvas, you can select a question bank to use for storing the questions. Then you can delete the quiz itself if you don't want it.

I'm not sure if the QTI format even supports a pure question bank, as opposed to a quiz...at least for me, the only export options are either entire course or individual quizzes, not question banks. I've been basing most of my work on reverse-engineering the Canvas QTI exports of quizzes, so without a pure question bank example to work off of, figuring this out would be difficult (assuming that it is even supported by QTI).

**Comment by rzach** [comment]
Ah now that you say that I think this is also how it works in Brightspace, so this is probably not terribly important.  But FTR here's an example (using QTI v2 however; looks like text2qti and Canvas use v1.2):
http://www.imsglobal.org/question/qtiv2p1/imsqti_implv2p1.html#section10020
You can close this then if you like.

**Comment by gpoore** [comment]
Thanks for the link. I will close this, but if Canvas does add QTI v2 support at some point, then I'll look into the additional capabilities.
