### ISSUE TITLE
Incorrect QTI version in manifest

### ISSUE THREAD

**Issue by ururk** [gpoore/text2qti#50]
README states:

```text2qti converts Markdown-based plain text files into quizzes in QTI format (version 1.2), which can be imported by Canvas and other educational software. ```

However, the version in the P1 manifest lists `1.1.3`:

https://github.com/gpoore/text2qti/blob/8e16684fe18dbcacec1474fbde8e9bfeef4c5838/text2qti/xml_imsmanifest.py#L21

**Comment by gpoore** [comment]
I could be wrong, but my impression was that this refers to an `IMS Content` packaging specification separate from QTI version (http://www.imsglobal.org/content/packaging/cpv1p1p3/imscp_infov1p1p3.html).

**Comment by ururk** [comment]
Oh, I think you are right - I'll let Canvas support know that the number refers to the packaging spec, and not the QTI version of the file itself.

**Comment by gpoore** [comment]
Are you having an issue with importing in Canvas? The templates I'm using are all based on what Canvas gives you when you export QTI. I only use Canvas and haven't had any issues myself (but also don't have access to new-style quizzes yet).

**Comment by ururk** [comment]
We are having issues with importing as a New Quiz. Still doesn't work anymore, but that's a separate issue we are trying to resolve with Canvas support (trying to escalate to a higher tier of support).

I agree with you on `1.1.3` being the packaging specification, and not the QTI version - sorry for any confusion! I implicitly trusted Canvas support, assumed they knew what they were referring to.
