### ISSUE TITLE
Does this GUI still work?

### ISSUE THREAD

**Issue by mjh55404** [gpoore/text2qti#57]
I have followed the installation instructions and tried to convert files without any success.

The GUI will not recognize the .md or .txt files in my folder.

<img width="1440" alt="Select a file" src="https://user-images.githubusercontent.com/110870034/183538124-b1a03865-6768-47da-9fa1-8adec1d8a424.png">

I also tried to convert with the command line and get the following error:

usage: text2qti [-h] [--version] [--latex-render-url LATEX_RENDER_URL]
                [--run-code-blocks] [--pandoc-mathml]
                file
text2qti: error: unrecognized arguments: 130 Chapter 1.txt

Please let me know if you have any suggestions. I have tried both ways and don't see what I am missing. I am trying to use my old Mac to convert a bunch of quiz files for upload into Canvas. 

Thanks

**Comment by gpoore** [comment]
I've suggest trying to get the command-line application working first. That error likely indicates that there is an issue with the command. What are you trying to run on the command line?

**Comment by mjh55404** [comment]
I locate the folder with the file in Finder.

I hold control and choose "new terminal at folder" and enter text2qti Crim 130 Chapter 1.txt in the terminal app. 

![Uploading Screen Shot 2022-08-08 at 9.38.44 PM.png…]()

![Uploading Screen Shot 2022-08-08 at 9.38.52 PM.png…]()

![Uploading Screen Shot 2022-08-08 at 9.39.15 PM.png…]()

I am happy to meet with you and share my screen if that is easier for you. I just don't see what I am doing wrong here.

**Comment by mjh55404** [comment]
I updated my post with screen captures above. Let me know if this helps.

**Comment by gpoore** [comment]
Try quotes around the file name: `text2qti "Crim 130 Chapter 1.txt"`.

**Comment by mjh55404** [comment]
I tried that and received: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/text2qti", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/text2qti/cmdline.py", line 82, in main
    raise Text2qtiError(f'File "{file_path}" does not exist')
text2qti.err.Text2qtiError: File "Crim 130 Chapter 1.txt." does not exist
Michaels-MBP-2:SensandNonsens_8e_WordTestBankFiles Michael$

**Comment by gpoore** [comment]
It looks like you might have an extra period in the file name (`.txt.` at the end). Maybe double-check that what is in quotes is exactly the file name, including the extension (`.txt`) but with nothing else.

**Comment by mjh55404** [comment]
I tried that and this time I get a bunch of errors stating: text2qti.err.Text2qtiError: Missing whitespace after "..."

I was trying to follow you feedback suggestions and entered the following for feedback with the page number.
Emaple:

![image](https://user-images.githubusercontent.com/110870034/183564190-2f59e146-79c1-48a6-af17-f9987f91f0ef.png)

**Comment by mjh55404** [comment]
Okay I removed my attempt to references and correct the spacing and it worked!

Now my questions is how do I properly include the reference to the answer? Something like Ref: Pages 15, 17

Thanks!

**Comment by gpoore** [comment]
Try something like `... REF 2,3`. I think you may have been missing the space after the periods.
