### ISSUE TITLE
Pushing QTIs to canvas

### ISSUE THREAD

**Issue by stevenbell** [gpoore/text2qti#58]
Thanks for this package!  I reluctantly needed to switch from a text-based quiz to using Canvas, and this tool has saved me many hours and my sanity.

In the spirit of avoiding Canvas' interface and doing things on the command-line, I've written a little script that pushes a QTI file to Canvas and configures it.  It's here for anyone that might find it useful; feel free to link, share, or modify as appropriate: https://gist.github.com/stevenbell/80d5f14b608e3392c068e822da48566d

**Comment by gpoore** [comment]
Thanks for the link! I've created a [wiki](https://github.com/gpoore/text2qti/wiki) and added the link to that page.
