### ISSUE TITLE
Normal code blocks

### ISSUE THREAD

**Issue by kenpower** [gpoore/text2qti#59]
Need to add some source code to the questions. So would like to preserve the original meaning of ```

Need a question that looks like:

==========================
Question 42: What does the following program output?

```
void main(){
    std::cout << "Hello";
}
```

- [ ] "Hello"
- [ ] "GoodBye"
- [ ] Empty string
- [ ] None of the above

**Comment by gpoore** [comment]
You want something like this:
``````
42. What does the following program output?

    ```
    void main(){
        std::cout << "Hello";
    }
    ```

[*] "Hello"
[]  "GoodBye"
[]  Empty string
[]  None of the above
``````

**Comment by kenpower** [comment]
Ah no! I've wasted so much time on this.

@gpoore your example works for me. Thanks.

The backticks need to be *indented*. (my backticks had no indent). I'm so used to github markdown.

**Comment by gpoore** [comment]
You probably want to think about the plain text format for quizzes as a wrapper around Markdown. Each individual chunk of text (question, answer, feedback, etc.) is Markdown. But the outermost level of text (no indent) is the text2qti plain-text quiz format. So the `42.` is a number indicating a question in text2qti format, and then the content of the question is (indented) Markdown. And `[]` indicates a choice, and the choice itself is (indented) Markdown. The fact that the Markdown is indented is only really more visible when multiple lines are involved. The indentation doesn't have to be 4 spaces, it just has to be the same for the whole chunk of text that makes up each element of a question.

**Comment by kenpower** [comment]
I didn't read [this section](https://github.com/gpoore/text2qti#descriptions-questions-choices-feedback-and-text-regions) carefully enough. Maybe a code block example there would be helpful.

I think the line in the section on executable blocks :"_The code block fences (```) must not be indented;_ " also threw me off.
