### ISSUE TITLE
Does not work with Blackboard

### ISSUE THREAD

**Issue by kenpower** [gpoore/text2qti#60]
Blackboard can (allegedly) import question **pools** (not quizzes) from QTI_1.2 files. In blackboard a "pool" is a collection of questions from which a subset can be selected to create a quiz. Blackboard does not allow quizzes to be imported from QTI files.

I tried importing a test2qti quiz, using the "import question pool" feature. The import was reported as "complete" with no errors by Blackboard, but the questions did not show up in  any of the pools nor as a quiz.

**Comment by gpoore** [comment]
text2qti only supports QTI v1.2 quizzes, not pools. There are also apparently sometimes QTI format incompatibilities between different learning management systems.

Unfortunately, I don't have time to work on any formats, questions types, or learning management systems beyond what I am currently actively using myself. If someone wants to submit a pull request to add additional formats, I'm happy to discuss that.
