### ISSUE TITLE
Code block indentation

### ISSUE THREAD

**Issue by benjaminb** [gpoore/text2qti#62]
In the README section on text regions it says code blocks must be indented "at least" as much as the first line of the question statement. What I'm experiencing is that code blocks have to be _exactly_ the same indentation in order to render properly on Canvas. For example, this markdown:

```
1. Consider the following code.

        ```java
        System.out.print("foo");
        System.out.print("bar");
        System.out.print("baz");
        ```

-   Be sure to review xyz
a)  It's `foo`
... Feedback for response a 
b)  1
... Feedback for this response b
*c) 5
... Feedback for this response c.
```

Renders on Canvas as this:
https://www.dropbox.com/s/u7qye58gzikpwf8/sshot.png?dl=0

Is this the intended behavior?

**Comment by gpoore** [comment]
For standard Markdown, anything indented by 4 or more spaces is treated as a code block. So everything indented under `Consider...` is treated as a code block, and appears verbatim. Backtick code blocks will only be treated as backtick code blocks if they are indented less than 4 spaces relative to the surrounding text.

**Comment by benjaminb** [comment]
Thanks for the fast response. I'm seeing somewhat different behavior. Here is text indented 4 spaces not appearing as code:
```
1. Choose the code used to print the following:

    "Hello world!"

- Feedback for any wrong answer
a)  Response a
... Feedback for Response a
b)  Response b
... Feedback for Response b
*c)  Response c
... Feedback for Response c
```

Canvas render: https://www.dropbox.com/s/lpfpgcu5pl3eg6n/shot1.png?dl=0

Trying to process a markdown file with a code fence indented less than 4 spaces relative to surrounding text causes an error:
````markdown
1. Choose the code used to print the following:

```
"Hello world!"
```
````
Error:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gt/bin/text2qti", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/gt/lib/python3.9/site-packages/text2qti/cmdline.py", line 125, in main
    quiz = Quiz(text, config=config, source_name=file_path.as_posix())
  File "/opt/miniconda3/envs/gt/lib/python3.9/site-packages/text2qti/quiz.py", line 729, in __init__
    raise Text2qtiError(f'In {self.source_name} on line {n+1}:\n{e}')
text2qti.err.Text2qtiError: In "block.md" on line 28:
Code block end missing code block start
```
Line 28 is the first triple-backtick above "Hello world!"

**Comment by gpoore** [comment]
For backtick code blocks, you want no indentation, relative to the indentation of the question text. In this case, relative to `Choose...`.
``````
1. Choose the code used to print the following:

   ```
   "Hello world!"
   ```
``````
For indented code blocks, the indentation is again relative to the current indentation (`Choose...`).
``````
1. Choose the code used to print the following:

       "Hello world!"

- Feedback for any wrong answer
a)  Response a
... Feedback for Response a
b)  Response b
... Feedback for Response b
*c)  Response c
... Feedback for Response c
``````

You want to think about the indentation something like this:
``````
**No indentation: text2qti wrapper syntax for Markdown**
|
|  **Indentation: Now using Markdown, everything below this must have at least this indentation**
|  |
1. Choose the code used to print the following:
|  |
|  ```
|  "Hello world!"
|  ```
|  |
``````

**Comment by benjaminb** [comment]
Got it thanks!
