### ISSUE TITLE
Query about duplicate question

### ISSUE THREAD

**Issue by NigelSlack** [gpoore/text2qti#63]
Hi,
I'm generating 200 questions in a group, and I include <font style="display:none">_text_</font> in each one, where 'text' is unique. I'm getting a 'Duplicate choice for question' response in spite of this. Is there a character length limit for the question - mine are roughly 340 characters, including the 'font' bit? I can't think what else would result in the 'duplicate' error, other than the unique' text' being beyond a line length limit.
Thanks.
Nigel Slack

**Comment by gpoore** [comment]
This shouldn't be caused by the actual question, but rather by the various possible answers including duplicates. So for instance a multiple-choice question where there are two or more identical choices provided. Can you give an example of a complete question that triggers this error?

**Comment by NigelSlack** [comment]
You're right - it was a duplicate value in the answers. Sorry about that. I'll close the case.

**Comment by NigelSlack** [comment]
I had duplicate values in the answer. Sorry.
