### ISSUE TITLE
Import feature - QTI to markdown?

### ISSUE THREAD

**Issue by javdansanyama** [gpoore/text2qti#64]
I really want to use this package with existing quizzes and question banks. With the current package is there any way to convert from QTI to markdown text? Thank you!

**Comment by gpoore** [comment]
Everything is designed for converting a text format based on Markdown (text2qti format) into QTI; there is no support for the reverse process.

To convert QTI into text2qti format, you would probably want to process the QTI using an XML parser, and then you'd need to write a converter to turn the XML tree into text2qti format. I don't think there will be much overlap between converting text2qti -> QTI and the reverse, so the existing text2qti code probably wouldn't help much.
