### ISSUE TITLE
Maximum group size?

### ISSUE THREAD

**Issue by skaug** [gpoore/text2qti#66]
Is there a limit to how many questions there can be in a group?

I experience problems when trying when going beyond 9 questions.

**Comment by gpoore** [comment]
I've used groups with dozens or probably even hundreds of questions. This is with Canvas. If you're using a different LMS, there might be limitations on group size. There might also be some sort of issue related to the particular questions or kinds of questions you are using...if that's the case, an example would be helpful.

**Comment by skaug** [comment]
Thanks. That eliminates my hypothesis regarding the limit in number of questions (I am using Canvas)

The error message, and two example question that fail are given below.

My hypothesis now is that the duplication is due to the line break in the question,
and because the second sentence "What is the variance of the sample" is the same. 
------------------

Text2qtiError: In "quiz.txt" on line 144:
Duplicate question

24. We observe the numbers -4, -1, -5.
	What is the variance of the sample
= 4.33 +- 0.01
25. We observe the numbers  5, -7, 7, -3.
	What is the variance of the sample
= 43.67 +- 0.01
----------------------------------------------

**Comment by gpoore** [comment]
Can you provide a complete example file that causes the issues? Just copying the two questions you provided into a file works for me.
