### ISSUE TITLE
QTI to markup?

### ISSUE THREAD

**Issue by bobkummerfeld** [gpoore/text2qti#67]
Not an issue with text2qti, but I've inherited a set of Canvas quizzes and would like to convert them to markdown so I can edit them in text form and then use text2qti to upload.    Any ideas on how to do that?

**Comment by gpoore** [comment]
You could convert/download the quizzes in QTI format, which is basically a zip archive containing XML files. Then you would need to parse the XML files. There are lots of existing libraries for Python and other languages. The more difficult part (probably more tedious really) would be extracting all of the important data for each question from the parsed XML, and then converting that to text2qti format.

If you are dealing with relatively simple questions, it might be possible to extract what you need with a simple regex search.

As a starting point, you might extract the XML files from the QTI, find the one that contains the questions, and just see how many different kinds of XML tags are actually relevant for the data you want to extract. That should give you a sense of the overall complexity for your particular case.

**Comment by bobkummerfeld** [comment]
Thanks Geoffrey. I'll take a look at it. I was hoping someone had done the hard work already 😀
