### ISSUE TITLE
lists in description...

### ISSUE THREAD

**Issue by olearydj** [gpoore/text2qti#68]
First off, this is going to make my life grand. Thank you! Managing quizzes and quiz banks in Canvas is the worst.

Everything is working well so far but I'm unable to track down an issue with a hierarchical markdown list in the description. The markdown below results in the error:

```
Syntax error; unexpected text, or incorrect indentation for a wrapped paragraph:
"	- PDMA BoK (BODY of Knowledge, not BOOK)"
```

I realize in typing this that I can just flatten this into two lists, but I'm fixated on the issue at hand because I'm certain it was working at one point.

Thanks again for sharing this great tool!

```
Quiz title: Quiz 1
Quiz description: This is an individual, open-book assignment covering the first three lectures, with a focus on content from the following readings:

	- PDMA BoK (BODY of Knowledge, not BOOK)
		- Introduction (pp. iii-xi)
		- Sections 1.1 thru 1.3 and 1.5 (pp. 5-11 and 17-18), Strategy
		- Section 1.7.3 (pp. 27-8), IP Primer and Strategy
		- Sections 3.1 (pp. 83-7), 3.3 thru 3.3.2 (90-8), and 3.3.5 (104-6), PI Processes
	- Papers and Articles
		- You Need an Innovation Strategy (Pisano 2015)
		- The Drivers of Success in New-Product Development (Cooper 2019)

shuffle answers: true
show correct answers: false
one question at a time: true
can't go back: false

GROUP
% PDMA BoK Introduction (pp. iii-xi)
pick: 5
points per question: 1

1. According to the PDMA BoK, product innovation can be defined as _____.
*a) The creation and introduction of a good or service that is either new or improved.
b) The process of making a product more affordable.
c) The process of marketing and selling a product.
d) The introduction of a product into a new market.

% and so on...
```

**Comment by olearydj** [comment]
sadly, flattening the content into two lists didn't work either, so I'm not sure what I'm overlooking here. markdown finickiness or user error?!

**Comment by gpoore** [comment]
This was a bug in parsing indentation...indentation starting with a tab wasn't supported. It's now fixed in the development version on GitHub, and a new release will be on PyPI soon. Sorry for the delay. I had about 10 months when I wasn't using text2qti due to a non-standard teaching schedule, and am just now getting back to fixing bugs and adding features again.
