### ISSUE TITLE
Wrong answer type

### ISSUE THREAD

**Issue by bobkummerfeld** [gpoore/text2qti#7]
Questions that expect an exact integer answer are installed in Canvas as answers with a range. For example:
1. What is the answer to the Universe and everything?
= 42

On Canvas the answer is "Answer in the Range:  between 42 and 42".
It should be "Exact Answer: 42"

The quiz was made with v0.3.0

**Comment by gpoore** [comment]
Thanks for pointing that out. I had missed a small difference in the XML between exact and range. It should be fixed now.

**Comment by bobkummerfeld** [comment]
Now working fine in latest version.
