### ISSUE TITLE
The reason for the indentation requirement

### ISSUE THREAD

**Issue by erlebach** [gpoore/text2qti#70]
Hi, 

I wonder why there is a need for indenting all lines after the first of a paragraph, with the further requirement that the start of the 2nd line is equal or beyond the start of the first line? Was it simpler to code, or is this a Canvas requirement? I ask because I am having GPT generate quizzes for me and it is difficult to ask it to conform to the indent requirement. I know I could write a preprocessing routine to fix all formatting issue. If somebody does write such a routine, perhaps it could be applied before the call to text2qti, just as C++ has its preprocessor (its effects are seen with the -E option to g++). Thanks.  Gordon.

**Comment by gpoore** [comment]
You probably want to think about indentation something like this:
```
**No indentation: text2qti wrapper syntax for Markdown**
|
|  **Indentation: Now using Markdown, everything below this must have at least this indentation**
|  |
1. Choose the code used to print the following:
|  |
|  ```
|  "Hello world!"
|  ```
|  |
```
If the content of each question/quiz element wasn't indented, then it would be ambiguous whether something like `1.` is the start of a quiz question, or the start of an enumerated list within a question.

**Comment by erlebach** [comment]
Thanks. Good points, which make sense.
